theme: minima
title: STALKING LENA
author: Lena Park
email: lenapark0122@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brag Sheet: I run varsity track and cross country throughout the entire year, am the secretary for EHS, and volunteer at The Chelsea as well as Healthy Kids' Running Series yearly. 

# social links
instagram: l.ena116 # DO NOT include the @ character, or else the build will fail!
github_username:  lenapark0122 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
